apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-agent-rb
subjects:
- kind: ServiceAccount
  name: build-agent
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: build-agent-role
  apiGroup: rbac.authorization.k8s.io