apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: build-agent-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","services","deployments", "secrets", "configmaps"]
  verbs: ["get", "delete", "list", "create"]