apiVersion: v1
data:
  MYSQL_DATABASE: "replace_with_base64data"
  MYSQL_PASSWORD: "replace_with_base64data"
  MYSQL_ROOT_PASSWORD: "replace_with_base64data"
  MYSQL_USER: "replace_with_base64data"
kind: Secret
metadata:
  creationTimestamp: null
  name: db-secret
